version: "3"

services:
  backend: 
    image: custom:15
  frontend:
    expose: 
      - "8080"
  scheduler:
    image: custom:15
  queue-long:
    image: custom:15
  queue-short:
    image: custom:15